[template.environment]
  GQL_HOST = "https://linen-hare-730472.hostingersite.com/graphql"
  NUXT_IMAGE_DOMAINS = "nashastore.netlify.app"

[build]
  command = "nuxt generate"

[images]
  remote_images = ["https://nashast.store/.*"]
